// Seed sweeps for Q14, Q26, Q37/Q50 (TURN-08). Usage: npx tsx sim/run.ts [--quick] [--workers N]
import { Worker } from 'node:worker_threads';
import { availableParallelism } from 'node:os';
import { mkdirSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import type { Task } from './tasks.js';

const args = process.argv.slice(2);
const quick = args.includes('--quick');
const workersArg = args.indexOf('--workers');
const WORKERS = workersArg >= 0 ? Number(args[workersArg + 1]) : Math.max(1, availableParallelism() - 1);
const N_ROUTE = quick ? 300 : 10000;
const N_WOLF = quick ? 200 : 2000;
const N_Q14 = quick ? 500 : 10000;
const N_GOOD = quick ? 200 : 2000;
const N_Q26 = quick ? 300 : 2000;

class Pool {
  private workers: Worker[] = [];
  private queue: { task: Task; resolve: (rows: unknown[]) => void; reject: (e: Error) => void }[] = [];
  private busy = new Map<Worker, (msg: { ok: boolean; rows?: unknown[]; error?: string }) => void>();
  constructor(n: number) {
    for (let i = 0; i < n; i++) {
      const w = new Worker(new URL('./worker.ts', import.meta.url), { execArgv: ['--import', 'tsx'] });
      w.on('message', (msg) => {
        const cb = this.busy.get(w);
        this.busy.delete(w);
        cb?.(msg);
        this.pump();
      });
      this.workers.push(w);
    }
  }
  run(task: Task): Promise<unknown[]> {
    return new Promise((resolve, reject) => {
      this.queue.push({ task, resolve, reject });
      this.pump();
    });
  }
  private pump() {
    for (const w of this.workers) {
      if (this.busy.has(w) || !this.queue.length) continue;
      const job = this.queue.shift()!;
      this.busy.set(w, (msg) => (msg.ok ? job.resolve(msg.rows!) : job.reject(new Error(msg.error))));
      w.postMessage({ id: 0, task: job.task });
    }
  }
  close() {
    for (const w of this.workers) void w.terminate();
  }
}

async function sweep<T>(pool: Pool, n: number, chunk: number, make: (from: number, to: number) => Task): Promise<T[]> {
  const parts: Promise<unknown[]>[] = [];
  for (let from = 0; from < n; from += chunk) parts.push(pool.run(make(from, Math.min(n, from + chunk))));
  return (await Promise.all(parts)).flat() as T[];
}

const pct = (a: number, b: number) => (b ? ((100 * a) / b).toFixed(1) + '%' : '—');
function quantile(xs: number[], q: number) {
  const s = [...xs].sort((a, b) => a - b);
  return s.length ? s[Math.min(s.length - 1, Math.floor(q * (s.length - 1)))]! : NaN;
}
const digest = (v: unknown) => createHash('sha256').update(JSON.stringify(v)).digest('hex').slice(0, 16);

interface Q14Row {
  seed: number;
  nights: { n: number; sat: number; arrived: number; third: number | null; last: number }[];
}

async function main() {
  const t0 = performance.now();
  const pool = new Pool(WORKERS);
  const lines: string[] = [];
  const summary: Record<string, unknown> = { workers: WORKERS, quick };
  lines.push('# Simulation report', '', `Generated by \`npx tsx sim/run.ts${quick ? ' --quick' : ''}\` with ${WORKERS} workers.`, '');

  // Q14
  const q14 = async (good: boolean, n: number) => {
    const rows = await sweep<Q14Row>(pool, n, good ? 25 : 250, (from, to) => ({ kind: 'q14', from, to, good, variants: 40 }));
    const nights = rows.flatMap((r) => r.nights.filter((x) => x.n >= 2));
    const four = nights.filter((x) => x.arrived >= 4);
    const pass3 = nights.filter((x) => x.sat >= 3 && x.third !== null && x.third <= 13).length;
    const all4 = four.filter((x) => x.sat >= 4).length;
    const used = nights.map((x) => x.last);
    return {
      nights: nights.length,
      pass3: pass3 / nights.length,
      all4: all4 / Math.max(1, four.length),
      meanSat: nights.reduce((a, x) => a + x.sat, 0) / nights.length,
      p50: quantile(used, 0.5),
      p90: quantile(used, 0.9),
      max: Math.max(...used),
      perNight: [2, 3, 4].map((k) => {
        const xs = nights.filter((x) => x.n === k);
        return { night: k, pass3: xs.filter((x) => x.sat >= 3 && x.third !== null && x.third <= 13).length / xs.length, all4: xs.filter((x) => x.sat >= 4).length / xs.length };
      }),
    };
  };
  const avg = await q14(false, N_Q14);
  const good = await q14(true, N_GOOD);
  summary.q14 = { average: avg, good };
  lines.push('## Q14 — load of Act I standard nights (nights 2–4, 15 ticks)', '');
  lines.push('Thresholds: average player ≥ 3 of 4 satisfied within ≤ 13 ticks in ≥ 80% of nights; good plan all 4 in ≥ 30%.', '');
  lines.push('| Policy | Nights | ≥3 sat. by tick 13 | All 4 sat. | Mean satisfied | Last serve tick p50 / p90 / max |', '|---|---|---|---|---|---|');
  for (const [name, r] of [['Average (greedy, no dialogue mistakes)', avg], ['Good plan (best of 40 on the same stream)', good]] as const)
    lines.push(`| ${name} | ${r.nights} | **${pct(r.pass3 * r.nights, r.nights)}** | **${pct(r.all4 * 1000, 1000)}** | ${r.meanSat.toFixed(2)} | ${r.p50} / ${r.p90} / ${r.max} |`);
  lines.push('', 'Per night (average / good):', '');
  lines.push('| Night | ≥3 by 13 avg | all 4 avg | ≥3 by 13 good | all 4 good |', '|---|---|---|---|---|');
  for (let i = 0; i < 3; i++)
    lines.push(`| ${avg.perNight[i]!.night} | ${pct(avg.perNight[i]!.pass3, 1)} | ${pct(avg.perNight[i]!.all4, 1)} | ${pct(good.perNight[i]!.pass3, 1)} | ${pct(good.perNight[i]!.all4, 1)} |`);
  lines.push('', `Verdict: average ${avg.pass3 >= 0.8 ? 'PASS' : 'FAIL'}; good plan ${good.all4 >= 0.3 ? 'PASS' : 'FAIL'}.`, '');

  // Load log nights 2–11 (Q50)
  const load = await sweep<{ seed: number; nights: { n: number; sat: number; arrived: number; last: number }[] }>(pool, N_Q26, 100, (from, to) => ({ kind: 'load', from, to }));
  lines.push('## Q50 — load log, nights 2–11 (average policy, tutorial vows accepted)', '', '| Night | Mean satisfied | Mean arrived | Last serve tick p50 / p90 / max |', '|---|---|---|---|');
  const loadRows: unknown[] = [];
  for (let n = 2; n <= 11; n++) {
    const xs = load.flatMap((r) => r.nights.filter((x) => x.n === n));
    const used = xs.map((x) => x.last);
    const row = { n, sat: xs.reduce((a, x) => a + x.sat, 0) / xs.length, arrived: xs.reduce((a, x) => a + x.arrived, 0) / xs.length, p50: quantile(used, 0.5), p90: quantile(used, 0.9), max: Math.max(...used) };
    loadRows.push(row);
    lines.push(`| ${n} | ${row.sat.toFixed(2)} | ${row.arrived.toFixed(2)} | ${row.p50} / ${row.p90} / ${row.max} |`);
  }
  summary.load = loadRows;

  // Q26
  lines.push('', '## Q26 — upgrade timing and income (average policy, buy order shelf → mittens → jar → chair, one per Межсветье)', '');
  lines.push('| Tram line | Shelf by night 6 | Mittens or chair by night 8 | Jar of Silence by night 10 | Income/night (nights 2–11) mean / p10 / p90 |', '|---|---|---|---|---|');
  const q26: Record<string, unknown> = {};
  for (const line of ['none', 'city', 'forest', 'river'] as const) {
    const rows = await sweep<{ purchases: Record<string, number>; income: number[] }>(pool, N_Q26, 100, (from, to) => ({ kind: 'q26', from, to, line }));
    const shelf = rows.filter((r) => (r.purchases.shelf ?? 99) <= 5).length;
    const mc = rows.filter((r) => Math.min(r.purchases.mittens ?? 99, r.purchases.chair ?? 99) <= 7).length;
    const jar = rows.filter((r) => (r.purchases.silence_jar ?? 99) <= 9).length;
    const inc = rows.map((r) => r.income.reduce((a, b) => a + b, 0) / Math.max(1, r.income.length));
    const mean = inc.reduce((a, b) => a + b, 0) / inc.length;
    q26[line] = { shelf: shelf / rows.length, mittensOrChair: mc / rows.length, jar: jar / rows.length, income: mean };
    lines.push(`| ${line} | ${pct(shelf, rows.length)} | ${pct(mc, rows.length)} | ${pct(jar, rows.length)} | ${mean.toFixed(1)} / ${quantile(inc, 0.1).toFixed(1)} / ${quantile(inc, 0.9).toFixed(1)} |`);
  }
  lines.push('', 'A purchase in the Межсветье after night N is available from night N+1; "by night 6" means bought after night ≤ 5.');
  summary.q26 = q26;

  // Endings
  lines.push('', '## Q37 / Q50 — ending routes', '');
  lines.push('| Mode | Route | Seeds | Reached | Other endings | Errors | Aggregate digest |', '|---|---|---|---|---|---|---|');
  const endings: Record<string, unknown> = {};
  const routeTimes: number[] = [];
  for (const mode of ['standard', 'granny', 'wolf'] as const)
    for (const route of ['wound', 'remember', 'new_spring', 'letter'] as const) {
      const n = mode === 'wolf' ? N_WOLF : N_ROUTE;
      const t = performance.now();
      const rows = await sweep<{ seed: number; ending: string | null; error: string | null }>(pool, n, 250, (from, to) => ({ kind: 'route', from, to, route, mode, variant: 'base' }));
      routeTimes.push((performance.now() - t) / n);
      const reached = rows.filter((r) => r.ending === route).length;
      const other: Record<string, number> = {};
      for (const r of rows) if (r.ending !== route) other[r.error ? 'error' : String(r.ending)] = (other[r.error ? 'error' : String(r.ending)] ?? 0) + 1;
      const failSeeds = rows.filter((r) => r.ending !== route).slice(0, 5).map((r) => r.seed);
      endings[`${mode}/${route}`] = { n, reached, other, failSeeds, digest: digest(rows) };
      lines.push(`| ${mode} | ${route} | ${n} | **${pct(reached, n)}** | ${JSON.stringify(other)} ${failSeeds.length ? '(e.g. seeds ' + failSeeds.join(', ') + ')' : ''} | ${rows.filter((r) => r.error).length} | \`${digest(rows)}\` |`);
    }
  summary.endings = endings;
  lines.push('', 'Wolf Hour is reported without a guarantee (Q66). A failing seed is reproduced with `npx tsx sim/replay-seed.ts <route> <mode> <seed>`.');

  // Variants
  lines.push('', '## Variants (acceptance criteria 1 and 6)', '', '| Variant | Route | Seeds | Reached | Note |', '|---|---|---|---|---|');
  const variants: Record<string, unknown> = {};
  for (const [route, variant, note] of [
    ['new_spring', 'base', 'never buys the double burner (Pryazhenets in night 11)'],
    ['new_spring', 'double', 'buys the double burner when affordable'],
    ['letter', 'zero', '0 sparks and 0 keys at every night start'],
    ['remember', 'zero', '0 sparks and 0 keys at every night start'],
  ] as const) {
    const n = quick ? 200 : 2000;
    const rows = await sweep<{ ending: string | null; double: number | null }>(pool, n, 250, (from, to) => ({ kind: 'route', from, to, route, mode: 'standard', variant }));
    const reached = rows.filter((r) => r.ending === route).length;
    const bought = rows.filter((r) => r.double !== null).length;
    variants[`${route}/${variant}`] = { n, reached, bought };
    lines.push(`| ${variant} | ${route} | ${n} | **${pct(reached, n)}** | ${note}; double burner bought in ${bought} runs |`);
  }
  summary.variants = variants;

  // Determinism under different parallelism (K28)
  const detN = quick ? 200 : 2000;
  const a = await sweep(pool, detN, 97, (from, to) => ({ kind: 'route', from, to, route: 'new_spring', mode: 'standard', variant: 'base' }));
  const single = new Pool(1);
  const b = await sweep(single, detN, detN, (from, to) => ({ kind: 'route', from, to, route: 'new_spring', mode: 'standard', variant: 'base' }));
  single.close();
  const same = digest(a) === digest(b);
  summary.determinism = { seeds: detN, same, digest: digest(a) };
  lines.push('', '## Determinism (K28)', '', `New Spring route, ${detN} seeds: ${WORKERS} workers × chunk 97 vs 1 worker × one chunk → digests \`${digest(a)}\` / \`${digest(b)}\` → ${same ? 'IDENTICAL' : 'DIFFERENT'}.`);

  const total = (performance.now() - t0) / 1000;
  const perCampaign = routeTimes.reduce((x, y) => x + y, 0) / routeTimes.length;
  summary.throughput = { totalSeconds: total, msPerCampaignWall: perCampaign };
  lines.push('', '## Throughput', '', `Total wall time ${total.toFixed(1)} s; ending sweeps ${perCampaign.toFixed(2)} ms wall per 12-night campaign with ${WORKERS} workers (≈ ${(1000 / perCampaign).toFixed(0)} campaigns/s).`);
  pool.close();
  mkdirSync('docs/reports', { recursive: true });
  const name = quick ? 'simulation-report-quick' : 'simulation-report';
  writeFileSync(`docs/reports/${name}.md`, lines.join('\n') + '\n');
  writeFileSync(`docs/reports/${name}.json`, JSON.stringify(summary, null, 2) + '\n');
  console.log(lines.join('\n'));
}

void main();
