// Generates docs/ASSET_PROVENANCE.md from assets/art/manifest.json and assets/audio/manifest.json.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
const rows = ['# Asset provenance', '', 'Generated by `node scripts/provenance.mjs` from the delivered manifests. Every shipped asset is original (project-owned procedural synthesis or Azure OpenAI image generation where the customer owns the output); commercial use is permitted (Q05). No AEGIS demo/lab media is shipped.', ''];
if (existsSync('assets/art/manifest.json')) {
  const m = JSON.parse(readFileSync('assets/art/manifest.json', 'utf8'));
  rows.push(`## Art (${m.assets.length} assets, ${(m.total_bytes / 1048576).toFixed(1)} MiB)`, '', '| ID | File | Tool / model | Review | License |', '|---|---|---|---|---|');
  for (const a of m.assets) rows.push(`| ${a.id} | assets/art/${a.file} | ${(a.source?.tool ?? '').split(' (')[0]} / ${a.source?.model ?? a.source?.operation ?? ''} | ${a.review?.status ?? ''} | ${(a.license ?? '').slice(0, 90)}… |`);
  rows.push('');
}
if (existsSync('assets/audio/manifest.json')) {
  const m = JSON.parse(readFileSync('assets/audio/manifest.json', 'utf8'));
  rows.push(`## Audio (${m.cues.length} cues)`, '', '| ID | Kind | Bus | Tool | License |', '|---|---|---|---|---|');
  for (const c of m.cues) rows.push(`| ${c.id} | ${c.kind} | ${c.bus} | ${(c.tool ?? '').split(' (')[0]} | ${(c.license ?? '').slice(0, 90)}… |`);
  rows.push('', 'Grandmother whispers are synthetic TTS for the vertical slice; release voices require PM approval (Q40).');
}
rows.push('', 'Code: original project code; AEGIS engine (MIT) vendored as packed SDK tarballs — see THIRD_PARTY_NOTICES.md.');
writeFileSync('docs/ASSET_PROVENANCE.md', rows.join('\n') + '\n');
console.log('wrote docs/ASSET_PROVENANCE.md', rows.length, 'lines');
